---
title: "'Exit Try' kann nur innerhalb einer Try-Anweisung verwendet werden."
ms.date: 07/20/2015
f1_keywords:
- vbc30393
- bc30393
helpviewer_keywords:
- BC30393
ms.assetid: b8651df3-a32f-478c-a6d8-aa0ef584155f
ms.openlocfilehash: 5280b041f1219ab9577e684c0814c13821ed9de0
ms.sourcegitcommit: f8c270376ed905f6a8896ce0fe25b4f4b38ff498
ms.translationtype: MT
ms.contentlocale: de-DE
ms.lasthandoff: 06/04/2020
ms.locfileid: "84397115"
---
# <a name="exit-try-can-only-appear-inside-a-try-statement"></a>'Exit Try' kann nur innerhalb einer Try-Anweisung verwendet werden.
`Exit Try` kann nur innerhalb einer `Try` -Blockanweisung angezeigt werden. Entweder ist die `Exit Try` -Anweisung redundant, oder die `Exit Try` -Anweisung befindet sich außerhalb des entsprechenden `Try` -Blocks.  
  
 **Fehler-ID:** BC30393  
  
## <a name="to-correct-this-error"></a>So beheben Sie diesen Fehler  
  
1. Suchen und entfernen Sie die unnötige `Exit Try` -Anweisung.  
  
2. Verschieben Sie die- `Exit Try` Anweisung an die entsprechende Stelle innerhalb des Codes.  
  
## <a name="see-also"></a>Weitere Informationen

- [Try...Catch...Finally-Anweisung](../language-reference/statements/try-catch-finally-statement.md)
