---
title: "\"Catch\" kann nicht hinter \"Finally\" in einer Try-Anweisung stehen"
ms.date: 07/20/2015
f1_keywords:
- vbc30379
- bc30379
helpviewer_keywords:
- BC30379
ms.assetid: 33d1278b-cf10-4c66-aaf8-08a4372f370b
ms.openlocfilehash: ab300d332dd82870901aec9bd57d8d5d8081a533
ms.sourcegitcommit: f8c270376ed905f6a8896ce0fe25b4f4b38ff498
ms.translationtype: MT
ms.contentlocale: de-DE
ms.lasthandoff: 06/04/2020
ms.locfileid: "84403770"
---
# <a name="catch-cannot-appear-after-finally-within-a-try-statement"></a>"Catch" kann nicht hinter "Finally" in einer Try-Anweisung stehen
Eine `Catch` -Anweisung wird im Code hinter dem `Finally` -Schl√ºsselwort angezeigt, das einen `Try` -Anweisungsblock beendet. `Catch` muss innerhalb eines `Try...Catch...Finally` -Anweisungsblocks angezeigt werden.  
  
 **Fehler-ID:** BC30379  
  
## <a name="to-correct-this-error"></a>So beheben Sie diesen Fehler  
  
1. Verschieben Sie die `Catch` -Anweisung im Code an eine geeignete Position.  
  
## <a name="see-also"></a>Weitere Informationen

- [Try...Catch...Finally-Anweisung](../language-reference/statements/try-catch-finally-statement.md)
